demeter-run/up

.gitignore, bin/bootstrap-cloud, bootstrap/.gitignore, bootstrap/aws-terraform.tf, bootstrap/backend-aws.tf.example, stage0/aws-terraform/.gitignore, stage0/aws-terraform/backend.tf.example, stage0/aws-terraform/main.tf
Bootstrap and complete stage0 for a cluster with the following `config.yaml`:
```yaml
cloud_provider: aws
availabilityZones: [eu-central-1b, eu-central-1c]
vpc:
cidr: 10.16.0.0/16
metadata:
region: eu-central-1
```
Closes #18
=> feat: bootstrap staging environment

stage0/aws-terraform/main.tf
Provide tolerations for CoreDNS to schedule on our initial nodes.
=> feat: cluster updates from eks module examples

stage0/aws-terraform/main.tf
=> feat(stage0): add ebs-csi add on driver

README.md, bin/bootstrap-cloud, bin/setup, bootstrap/README.md, config.yaml.example
=> chore(docs): cluster bootstrap and sharing

stage3/kong.tf
=> feat(stage3): wire up Kong metrics to Prometheus

global/README.md
Document configuring a new provider
Closes #34
=> chore(docs): creating a global tunnel for a provider

stage3/cloudflared.tf
=> feat(stage3): add servicemonitor for provider metrics

stage0/aws-terraform/README.md
=> doc(stage0): AWS command to get EKS kubeconfig

README.md
=> doc: cluster setup

bin/bootstrap-cloud, bin/setup, common/defaults-gcp.yaml, global/README.md, stage0/aws-terraform/main.tf, stage0/gcp-terraform/main.tf
This also puts the cluster into a GCP region and instance types which are all supported together.
=> fix: errors discovered while bootstrapping gcp from scratch

README.md, config.yaml.example, stage1/README.md, stage2/README.md, stage3/README.md
=> docs: updated docs

stage0/gcp-terraform/main.tf, stage3/kupo.tf, stage3/main.tf, stage3/nodes.tf, stage3/variables.tf
Fixes #126 
Kupo logs
```
{"severity":"Info","timestamp":"2024-08-18T17:00:13.007751203Z","thread":"18","message":{"Consumer":{"tag":"ConsumerRollForward","slotNo":5051683,"inputs":2625,"binaryData":4,"scripts":13}},"version":"v2.9.0+61ad7e"}
{"severity":"Info","timestamp":"2024-08-18T17:00:16.831518092Z","thread":"18","message":{"Consumer":{"tag":"ConsumerRollForward","slotNo":5056013,"inputs":2462,"binaryData":0,"scripts":9}},"version":"v2.9.0+61ad7e"}
```
=> feat: add Kupo

stage3/kupo.tf, stage3/ogmios.tf, stage3/variables.tf
Fixes: #127 
Ogmios logs
```
{"severity":"Info","timestamp":"2024-08-20T00:21:11.10365403Z","thread":"17","message":{"Health":{"tag":"HealthTick","status":{"startTime":"2024-08-19T23:17:10.194592154Z","lastKnownTip":{"slot":57457271,"id":"6a03257b6804def6904b343c068534e3cbcc2260fd984710469760cf338a3a22","height":2400809},"lastTipUpdate":"2024-08-20T00:21:11.102566796Z","networkSynchronization":1.00000,"currentEra":"conway","metrics":{"activeConnections":0,"runtimeStats":{"cpuTime":7879107233,"currentHeapSize":498,"gcCpuTime":6981499867,"maxHeapSize":503},"sessionDurations":{"max":0,"mean":0,"min":0},"totalConnections":0,"totalMessages":0,"totalUnrouted":0},"connectionStatus":"connected","currentEpoch":665,"slotInEpoch":1271,"version":"v6.5.0 …
```
=> feat: add support for Ogmios

global/cloudflare.tf
This mostly removes comments from items which are enabled in Pro and cannot be configured in the free plan.
=> feat: cloudflare pro items in global

modules/common/cert-manager/stage2/main.tf, modules/common/cert-manager/stage2/variables.tf, stage2/env.auto.tfvars.example, stage2/main.tf, stage2/variables.tf
Fixes #125
```
Last Transition Time:  2024-09-10T07:53:32Z
Message:               Certificate request has been approved by cert-manager.io
Reason:                cert-manager.io
Status:                True
Type:                  Approved
```
=> feat: add cluster_issuer support for CloudFlare to cert-manager

stage3/kupo.tf, stage3/nodes.tf
Fix - remove volume-name for Kubernetes controller to provision a PersistentVolume dynamically
=> fix: resolve discrepancy to match cert-manager configuration

bin/bootstrap-cloud, bin/setup
Closes https://github.com/demeter-run/up/issues/144
=> feat: add kubectl initial setup to bin/setup

bin/setup, config.yaml.example, stage2/env.auto.tfvars.example
=> fix: update bin/setup to generate env.auto.tfvars

stage2/variables.tf
https://github.com/orgs/demeter-run/packages/container/fabric-daemon/302297445?tag=99e71e3af72f6c734b82535052822a89f59921ee
=> chore: update demeter fabric daemon image tag

stage3/utxorpc.tf
=> fix(utxorpc): add ext-utxorpc CRDs

modules/common/o11y/stage2/alertmanager.tf, modules/common/o11y/stage2/grafana.tf, modules/common/o11y/stage2/variables.tf, stage2/.terraform.lock.hcl, stage2/env.auto.tfvars.example, stage2/main.tf, stage2/variables.tf
set default to not install grafana or alert manager, add config option to enable install
=> feat: add flags for grafana and alert manager

global/cloudflare.tf, global/env.auto.tfvars.example
It's not just the preview network. I was thrown off by the SSL certificate.
=> refactor(global): rename kupo to remove network specific moniker

global/cloudflare.tf, global/env.auto.tfvars.example
This adds ogmios and alphabetizes the sections.
=> feat(global): ogmios load balancer

global/cloudflare.tf, global/env.auto.tfvars.example
Use a single `demeter_providers` data structure to provide a list of providers, with the provider's capabilities and endpoint addresses codified.
=> refactor(global): single demeter_providers data structure

global/cloudflare.tf, global/env.auto.tfvars.example
Move demeter_providers to a local and split the tunnels secrets to its own variable.
=> refactor(global): split tunnel secrets, use local providers

global/cloudflare.tf
Split kupo into preview, preprod, and mainnet networks.
=> feat(global): kupo split networks load balancing

common/defaults-gcp.yaml, stage3/kupo.tf, stage3/variables.tf
- bump ext-cardano-kupo with node-affinity support
- fix a label
- add default values for node-affiity
=> feat(ext-kupo): add support for node affinity
